// <auto-generated/>
using System;
namespace Microsoft.Docs.Build
{
    internal static partial class Errors
    {
       public static class T4 {

             public static Error Method1 (object dependencyRepoHref)
            => new Error(ErrorLevel.Error, "need-restore-demo", $"Cannot find dependency '{dependencyRepoHref}', did you forget to run `docfx restore`?");
             public static Error Method2 (object dependencyRepoHref)
            => new Error(ErrorLevel.Error, "need-restore-demo", $"Cannot find dependency '{dependencyRepoHref}', did you forget to run `docfx restore`?");
             public static Error Method3 (object dependencyRepoHref)
            => new Error(ErrorLevel.Error, "need-restore-demo", $"Cannot find dependency '{dependencyRepoHref}', did you forget to run `docfx restore`?");
             public static Error Method4 (object dependencyRepoHref)
            => new Error(ErrorLevel.Error, "need-restore-demo", $"Cannot find dependency '{dependencyRepoHref}', did you forget to run `docfx restore`?");
             public static Error Method5 (object dependencyRepoHref)
            => new Error(ErrorLevel.Error, "need-restore-demo", $"Cannot find dependency '{dependencyRepoHref}', did you forget to run `docfx restore`?");
             public static Error Method6 (object dependencyRepoHref)
            => new Error(ErrorLevel.Error, "need-restore-demo", $"Cannot find dependency '{dependencyRepoHref}', did you forget to run `docfx restore`?");
             public static Error Method7 (object dependencyRepoHref)
            => new Error(ErrorLevel.Error, "need-restore-demo", $"Cannot find dependency '{dependencyRepoHref}', did you forget to run `docfx restore`?");
             public static Error Method8 (object dependencyRepoHref)
            => new Error(ErrorLevel.Error, "need-restore-demo", $"Cannot find dependency '{dependencyRepoHref}', did you forget to run `docfx restore`?");
             public static Error Method9 (object dependencyRepoHref)
            => new Error(ErrorLevel.Error, "need-restore-demo", $"Cannot find dependency '{dependencyRepoHref}', did you forget to run `docfx restore`?");
             public static Error Method10 (object dependencyRepoHref)
            => new Error(ErrorLevel.Error, "need-restore-demo", $"Cannot find dependency '{dependencyRepoHref}', did you forget to run `docfx restore`?");
            }
    }
}
